replicaCount: 1

image:
  repository: <dockerhub-username>/stress-backend
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: LoadBalancer
  port: 5002

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

env:
  - name: API_PORT
    value: "5002"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30
