apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: { { include "backend.fullname" . } }
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: { { include "backend.fullname" . } }
  minReplicas: { { .Values.hpa.minReplicas } }
  maxReplicas: { { .Values.hpa.maxReplicas } }
  targetCPUUtilizationPercentage:
    { { .Values.hpa.targetCPUUtilizationPercentage } }
