apiVersion: v1
kind: Service
metadata:
  name: be-svc
  namespace: default
spec:
  selector:
    app: be-svc
  type: LoadBalancer
  ports:
    - name: be-svc
      protocol: TCP
      port: 80
      targetPort: 5002
