apiVersion: v1
kind: Service
metadata:
  name: fe-svc
  namespace: default
spec:
  selector:
    app: frontend-app
  type: LoadBalancer
  ports:
    - name: fe-svc
      protocol: TCP
      port: 80
      targetPort: 3000
